export const DemoData = {
  demoPosts: [
    {
      username: 'Flutter Expert',
      profImage: require('../assets/images/default_avatar.png'),
      postUrl: 'https://picsum.photos/600/400?random=1',
      description: 'Just completed an amazing Flutter course! The widget system is so powerful for building beautiful UIs. Learning Flutter has been an incredible journey filled with exciting challenges and rewarding outcomes.',
      likes: ['user1', 'user2', 'user3', 'user4', 'user5'],
      postId: 'post1',
      datePublished: new Date(Date.now() - 2 * 60 * 60 * 1000),
      category: 'study',
      educationLevel: 'college',
      estimatedReadTime: 5,
      tags: ['Flutter', 'Dart', 'Programming', 'Mobile Development'],
    },
    {
      username: 'Tech Intern',
      profImage: require('../assets/images/default_avatar.png'),
      postUrl: 'https://picsum.photos/600/400?random=2',
      description: 'Excited to share that I got an internship at Google! The interview process was challenging but worth it. Looking forward to learning from the best in the industry.',
      likes: ['user1', 'user4', 'user5', 'user6'],
      postId: 'post2',
      datePublished: new Date(Date.now() - 5 * 60 * 60 * 1000),
      category: 'internship',
      educationLevel: 'college',
      estimatedReadTime: 3,
      tags: ['Internship', 'Google', 'Career', 'Tech'],
    },
  ],

  demoUsers: [
    {
      username: 'Study Buddy',
      photoUrl: require('../assets/images/default_avatar.png'),
      userType: 'student',
      followers: 234,
      following: 156,
      bio: 'Passionate about learning and sharing knowledge',
    },
    {
      username: 'Code Master',
      photoUrl: require('../assets/images/default_avatar.png'),
      userType: 'educator',
      followers: 567,
      following: 89,
      bio: 'Computer Science Professor | Flutter Enthusiast',
    },
  ],

  demoShorts: [
    {
      videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
      title: 'Learn Flutter in 5 Minutes',
      creator: 'Flutter Master',
      likes: '12K',
      comments: '1.2K',
      views: '150K',
    },
    {
      videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
      title: 'Dart Programming Basics',
      creator: 'Dart Guru',
      likes: '8K',
      comments: '800',
      views: '89K',
    },
    {
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    title: 'Learn Flutter in 5 Minutes',
    creator: 'Flutter Master',
    likes: '12K',
    comments: '1.2K',
    views: '150K',
    },
    {
      videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
      title: 'Dart Programming Basics',
      creator: 'Dart Guru',
      likes: '8K',
      comments: '800',
      views: '89K',
    },
    {
      videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
      title: 'React Native vs Flutter',
      creator: 'Mobile Dev Expert',
      likes: '15K',
      comments: '2.3K',
      views: '210K',
    },
    {
      videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
      title: 'JavaScript Fundamentals',
      creator: 'JS Wizard',
      likes: '20K',
      comments: '3.1K',
      views: '450K',
    },
    {
      videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
      title: 'Python for Beginners',
      creator: 'Python Pro',
      likes: '25K',
      comments: '4.2K',
      views: '680K',
    },
    {
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    title: 'Learn Flutter in 5 Minutes',
    creator: 'Flutter Master',
    likes: '12K',
    comments: '1.2K',
    views: '150K',
  },
  {
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    title: 'Dart Programming Basics',
    creator: 'Dart Guru',
    likes: '8K',
    comments: '800',
    views: '89K',
  },
  {
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    title: 'React Native vs Flutter',
    creator: 'Mobile Dev Expert',
    likes: '15K',
    comments: '2.3K',
    views: '210K',
  },
  {
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    title: 'JavaScript Fundamentals',
    creator: 'JS Wizard',
    likes: '20K',
    comments: '3.1K',
    views: '450K',
  },
  {
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    title: 'Python for Beginners',
    creator: 'Python Pro',
    likes: '25K',
    comments: '4.2K',
    views: '680K',
  },
  
  ],

  demoOpportunities: [
    {
      type: 'Internship',
      title: 'Flutter Developer Intern',
      company: 'Tech Solutions Inc.',
      duration: '3 months',
      stipend: '$1,500/month',
      deadline: '2024-02-15',
      description: 'Join our mobile development team to build amazing Flutter applications. Perfect for students looking to gain real-world experience.',
      tags: ['Flutter', 'Dart', 'Mobile', 'Internship'],
    },
    {
      type: 'Scholarship',
      title: 'STEM Excellence Scholarship',
      company: 'National Education Foundation',
      amount: '$10,000',
      deadline: '2024-04-30',
      description: 'Scholarship for outstanding students pursuing STEM fields. Based on academic excellence and innovation.',
      tags: ['STEM', 'Merit-based', 'Science', 'Technology'],
    },
  ],
};